
-- SMARTNEWS EXERCISE
-- DAVIS WEI
-- 2022-03-02
-- ALL CSV FILES WERE LOAED INTO SQL SERVER 
-- ALL TABLES NAMES ARE SAME AS FILE NAMES
-- STEP 1:  GET THE INSTALL_COUNT/D3_COUNT/D7_COUNT
-- PARTITIONED BY IMPRESSION_DATE, PUBLISHER, CREATIVE_CODE
WITH install AS
(
	SELECT 
	CAST(IMPRESSION_DT AS DATE) AS IMPRESSION_DATE,
	CAMPAIGN_ID,
	PUBLISHER,
	CREATIVE_CODE,
	CREATIVE_NAME,
	COUNT(DEVICE_ID) AS INSTALL_COUNT
	FROM dev.streaming_data
	WHERE EVENT_TYPE = 'install'
	GROUP BY 1,2,3,4,5
), 
d3 AS
(
	SELECT 
	CAST(IMPRESSION_DT AS DATE) AS IMPRESSION_DATE,
	CAMPAIGN_ID,
	PUBLISHER,
	CREATIVE_CODE,
	CREATIVE_NAME,
	COUNT(DEVICE_ID) AS D3_COUNT
	FROM dev.streaming_data
	WHERE EVENT_TYPE = 'd3_retained'
	GROUP BY 1,2,3,4,5
), 
d7 AS
(
	SELECT 
	CAST(IMPRESSION_DT AS DATE) AS IMPRESSION_DATE,
	CAMPAIGN_ID,
	PUBLISHER,
	CREATIVE_CODE,
	CREATIVE_NAME,
	COUNT(DEVICE_ID) AS D7_COUNT
	FROM dev.streaming_data
	WHERE EVENT_TYPE = 'd7_retained'
	GROUP BY 1,2,3,4,5
),
-- STEP 2: CALCULATE THE UNIT COST FOR INSTALL, D3, AND D7
-- PARTITIONED BY IMPRESSION_DATE, PUBLISHER, CREATIVE_CODE
UNIT_COST AS
(
	SELECT 
	SS.DT AS IMPRESSION_DATE,
	SS.CAMPAIGN_ID,
	SS.PUBLISHER,
	SS.CREATIVE_CODE,
	SS.CREATIVE_NAME,
	SS.SPEND,
	install.install_count,
	SS.SPEND/install.INSTALL_COUNT AS COST_PER_INSTALL,
	d3.D3_COUNT,
	SS.SPEND/d3.D3_COUNT AS COST_PER_D3,
	d7.D7_COUNT,
	SS.SPEND/d7.D7_COUNT AS COST_PER_D7
	FROM dev.streaming_spend SS 
	LEFT JOIN install on 
	(SS.CREATIVE_CODE = install.CREATIVE_CODE 
	AND SS.CAMPAIGN_ID = install.CAMPAIGN_ID
	AND SS.DT = install.IMPRESSION_DATE)
	LEFT JOIN d3 on
	(SS.CREATIVE_CODE = d3.CREATIVE_CODE 
	AND SS.CAMPAIGN_ID = d3.CAMPAIGN_ID
	AND SS.DT = d3.IMPRESSION_DATE)
	LEFT JOIN d7 on
	(SS.CREATIVE_CODE = d7.CREATIVE_CODE 
	AND SS.CAMPAIGN_ID = d7.CAMPAIGN_ID
	AND SS.DT = d7.IMPRESSION_DATE)
)

-- STEP 3: APPLY THE UNIT COST TO THE INSTALL BASED ON CONVERSION_WINDOW
, CPI_BASE AS
(
	SELECT 
	CAST(IMPRESSION_DT AS DATE) AS IMPRESSION_DATE,
	CAST(EVENT_DATETIME AS DATE) AS EVENT_DATE,
	CAST(EVENT_DATETIME AS DATE) - CAST(IMPRESSION_DT AS DATE) AS CONVERSION_WINDOW,
	SD.CAMPAIGN_ID,
	SD.PUBLISHER,
	SD.CREATIVE_CODE,
	SD.CREATIVE_NAME,
	UC.COST_PER_INSTALL,
	COUNT(DEVICE_ID) AS INSTALL_COUNT,
	COUNT(DEVICE_ID) * UC.COST_PER_INSTALL AS INSTALL_COST_SUM
	FROM dev.streaming_data SD
	INNER JOIN UNIT_COST UC ON
	(
	SD.IMPRESSION_DT = UC.IMPRESSION_DATE AND
	SD.CAMPAIGN_ID = UC.CAMPAIGN_ID AND
	SD.CREATIVE_CODE = UC.CREATIVE_CODE
	)
	WHERE EVENT_TYPE = 'install'
	GROUP BY 1,2,3,4,5,6,7,8
	ORDER BY CONVERSION_WINDOW ASC
)
, CPD3_BASE AS
(
	SELECT 
	CAST(IMPRESSION_DT AS DATE) AS IMPRESSION_DATE,
	CAST(EVENT_DATETIME AS DATE) AS EVENT_DATE,
	CAST(EVENT_DATETIME AS DATE) - CAST(IMPRESSION_DT AS DATE) AS CONVERSION_WINDOW,
	SD.CAMPAIGN_ID,
	SD.PUBLISHER,
	SD.CREATIVE_CODE,
	SD.CREATIVE_NAME,
	UC.COST_PER_D3,
	COUNT(DEVICE_ID) AS D3_COUNT,
	COUNT(DEVICE_ID) * UC.COST_PER_D3 AS D3_COST_SUM
	FROM dev.streaming_data SD
	INNER JOIN UNIT_COST UC ON
	(
	SD.IMPRESSION_DT = UC.IMPRESSION_DATE AND
	SD.CAMPAIGN_ID = UC.CAMPAIGN_ID AND
	SD.CREATIVE_CODE = UC.CREATIVE_CODE
	)
	WHERE EVENT_TYPE = 'd3_retained'
	GROUP BY 1,2,3,4,5,6,7,8
	ORDER BY CONVERSION_WINDOW ASC
)
, CPD7_BASE AS
(
	SELECT 
	CAST(IMPRESSION_DT AS DATE) AS IMPRESSION_DATE,
	CAST(EVENT_DATETIME AS DATE) AS EVENT_DATE,
	CAST(EVENT_DATETIME AS DATE) - CAST(IMPRESSION_DT AS DATE) AS CONVERSION_WINDOW,
	SD.CAMPAIGN_ID,
	SD.PUBLISHER,
	SD.CREATIVE_CODE,
	SD.CREATIVE_NAME,
	UC.COST_PER_D7,
	COUNT(DEVICE_ID) AS D7_COUNT,
	COUNT(DEVICE_ID) * UC.COST_PER_D7 AS D7_COST_SUM
	FROM dev.streaming_data SD
	INNER JOIN UNIT_COST UC ON
	(
	SD.IMPRESSION_DT = UC.IMPRESSION_DATE AND
	SD.CAMPAIGN_ID = UC.CAMPAIGN_ID AND
	SD.CREATIVE_CODE = UC.CREATIVE_CODE
	)
	WHERE EVENT_TYPE = 'd7_retained'
	GROUP BY 1,2,3,4,5,6,7,8
	ORDER BY CONVERSION_WINDOW ASC
)

SELECT 
CPI_BASE.*,
CPD3_BASE.COST_PER_D3,
CPD3_BASE.D3_COUNT,
CPD3_BASE.D3_COST_SUM,
CPD7_BASE.COST_PER_D7,
CPD7_BASE.D7_COUNT,
CPD7_BASE.D7_COST_SUM
FROM CPI_BASE -- 1506
LEFT JOIN CPD3_BASE 
ON (
CPI_BASE.IMPRESSION_DATE = CPD3_BASE.IMPRESSION_DATE AND
CPI_BASE.EVENT_DATE = CPD3_BASE.EVENT_DATE AND
CPI_BASE.CAMPAIGN_ID = CPD3_BASE.CAMPAIGN_ID AND
CPI_BASE.CREATIVE_CODE = CPD3_BASE.CREATIVE_CODE)
LEFT JOIN CPD7_BASE 
ON (
CPI_BASE.IMPRESSION_DATE = CPD7_BASE.IMPRESSION_DATE AND
CPI_BASE.EVENT_DATE = CPD7_BASE.EVENT_DATE AND
CPI_BASE.CAMPAIGN_ID = CPD7_BASE.CAMPAIGN_ID AND
CPI_BASE.CREATIVE_CODE = CPD7_BASE.CREATIVE_CODE)

